# Generated by Django 4.2.7 on 2023-11-20 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('definition', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('dtype', models.TextField(blank=True, choices=[('bool', 'Bool'), ('label', 'Label'), ('rank', 'Rank')])),
                ('definition', models.TextField(null=True)),
                ('notes', models.TextField(blank=True)),
                ('metric', models.ManyToManyField(help_text='Select a metric for this column', related_name='feature', to='glossary.metric')),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.ImageField(upload_to='examples/')),
                ('feature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example', to='glossary.feature')),
            ],
        ),
    ]
