# Generated by Django 4.2.7 on 2023-11-23 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0002_intro_example_created_at_feature_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Example',
        ),
    ]
