# Generated by Django 4.2.7 on 2023-11-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0003_delete_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_type', models.TextField(choices=[('user', 'User'), ('model', 'Model')], default='model')),
                ('speaker_label', models.CharField(blank=True, max_length=20)),
                ('body', models.TextField()),
            ],
        ),
    ]
