# Generated by Django 4.2.7 on 2023-11-23 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0004_turn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Turn',
        ),
    ]
