# Generated by Django 4.2.7 on 2023-11-23 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0006_example'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Example',
            new_name='Conversation',
        ),
    ]
