# Generated by Django 4.2.7 on 2023-11-23 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0007_rename_example_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_type', models.TextField(choices=[('user', 'User'), ('model', 'Model')], default='model')),
                ('speaker_label', models.CharField(blank=True, max_length=20)),
                ('body', models.TextField()),
                ('conversation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='glossary.conversation')),
            ],
        ),
    ]
