# Generated by Django 4.2.7 on 2023-11-23 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0009_turn_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation', to='glossary.feature'),
        ),
        migrations.AlterField(
            model_name='turn',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turn', to='glossary.conversation'),
        ),
    ]
