# Generated by Django 4.2.7 on 2023-11-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0010_alter_conversation_feature_alter_turn_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.SlugField(unique=True),
        ),
    ]
