# Generated by Django 4.2.7 on 2023-11-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0012_alter_feature_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
